export { Hero } from './hero'
export { WhatIDo } from './whatido'
export { Projects } from './projects'
export { AboutMe } from './aboutme'
export { ContactSection } from './contact'
export { Footer } from './footer'